app:
  profile: prod
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%highlight(%5p)) %clr(${PID:- }){magenta} %clr([%10.10t]){faint} %clr(%-40.40logger{39}){cyan} %clr(%-20.20M){yellow} %clr(:){faint} %m%n%wEx"
  path: ./logs/springboot/local
  file: bootLog
  file.max-history: 60
  file.max-size: 100MB
  level:
    root: info
    com.youunsiktech.boot: info
    com.zaxxer.hikari: info
    com.querydsl.sql: info
    org.springframework:
      jdbc.core.JdbcTemplate: info
      batch.item.database: info
databases:
  batch:
    write:
      host:
      port: 3306
      db:
      username:
      password:
      maxPoolSize: 50
      minimumIdle: 50
      connectionTimeOut: 300000
      validationTimeOut: 1000
    read:
      host:
      port: 3306
      db:
      username:
      password:
      maxPoolSize: 50
      minimumIdle: 50
      connectionTimeOut: 300000
      validationTimeOut: 1000